[package]
name = "vnix-musl"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.30.5"
linuxfb = "0.3.1"
crossterm = "0.27.0"
spin = "0.9.5"
rand = "0.8.5"
async-trait = "0.1.83"

vnix = {path = "../"}
